spring.application.name=WebApp
server.port=8081

#spring.datasource.url=jdbc:h2:mem:saraung
spring.datasource.url=jdbc:h2:file:D:/SpringBoot/WebApp/data/saraung

spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=
imagekit.public.key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private.key=${IMAGEKIT_PRIVATE_KEY}
imagekit.url.endpoint=${IMAGEKIT_URL_ENDPOINT}

